//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentID { get; set; }
        public string message { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> requestID { get; set; }
    
        public virtual User User { get; set; }
    }
}
